version: "3.7"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: "no"
    environment:
      MONGO_INITDB_DATABASE: products_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017