server:
  port: 8082

cors:
  url-allowed: http://192.168.1.4:8081

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

spring:
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: user
      password: password
  # Conexion DB PostgreSQL
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  application:
    name: shopnow-user-ms
hibernate:
  hbm2ddl:
    auto:
eureka:
  client:
  registerWithEureka: true
  fetchRegistry: true
  service-url:
    defaultZone: http://localhost:8761/eureka