server:
  port: 8082

cors:
  url-allowed: http://192.168.1.4:8081

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

spring:
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: user
      password: password
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: user_products_db
      port: 27017
      host: localhost

  application:
    name: shopnow-user-ms
eureka:
  client:
  registerWithEureka: true
  fetchRegistry: true
  service-url:
    defaultZone: http://localhost:8761/eureka